<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorMonaco" />
    <PackageReference Include="TinyMCE.Blazor" />
    <PackageReference Include="Volo.Abp.AutoMapper"/>
    <PackageReference Include="Volo.CmsKit.Admin.Application.Contracts" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Zyknow.Abp.GroupComponent.FluentDesignUI\Zyknow.Abp.GroupComponent.FluentDesignUI.csproj" />
    <ProjectReference Include="..\..\FluentDesignTheme\Zyknow.Abp.AspnetCore.Components.Web.FluentDesignTheme\Zyknow.Abp.AspnetCore.Components.Web.FluentDesignTheme.csproj"/>
    <ProjectReference Include="..\Zyknow.Abp.CmsKit.Blazor.Common.FluentDesignUI\Zyknow.Abp.CmsKit.Blazor.Common.FluentDesignUI.csproj" />
  </ItemGroup>
 
</Project> 